/**
 * Output-correctness oracles for cssomnom's recovery (error-tolerant) parser.
 *
 * A recovery parser must not crash — so crash-signals alone find nothing here.
 * These oracles instead assert *relations* that must hold for every input,
 * valid or malformed. They are deliberately reference-free:
 *
 *   1. fixpoint      parse → serialize(cssText) → re-parse → re-serialize.
 *                    The second serialization must equal the first. Any drift
 *                    means the parser mis-reads its own canonical output
 *                    (parser/serializer disagreement) — a bug regardless of
 *                    whether the original input was valid.
 *   2. conservation  css-syntax-3 tokenization partitions the preprocessed
 *                    input stream exactly: no code point dropped, duplicated,
 *                    or reordered. Checked via offset contiguity over content
 *                    tokens AND by concatenating every token's `originalText`
 *                    INCLUDING the trailing <EOF-token>, whose originalText may
 *                    be non-empty (it absorbs consumed trailing comments:
 *                    #consume-token step 1 + #consume-comment "returns
 *                    nothing"; § 8 #serialization permits keeping comments).
 *   3. refixation    Re-tokenizing the concatenated token text (again over ALL
 *                    tokens including EOF) must yield the identical token
 *                    sequence (tokenizer is a fixpoint too).
 *   4. streaming     Chunked StreamingTokenizer ingestion must produce the
 *                    same (type, originalText) sequence as one-shot tokenize().
 *
 * Equivalence relation note: oracle (1) compares serialized *canonical* forms,
 * not ASTs, so spec-sanctioned lossy normalization (comment removal, whitespace
 * collapsing, case canonicalization) happens once at stage s1 and cannot create
 * false positives — see fuzz/oracles/README.md ("Equivalence relation").
 *
 * This module NEVER mutates repo state and never files KIs. It only reports
 * findings; triage/dedup/KI filing stays a human-supervised pipeline step.
 */

import { tokenize } from '../../../src/tokenizer.ts';
import { StreamingTokenizer } from '../../../src/streaming-tokenizer.ts';
import { parse } from '../../../src/parser.ts';
import type { Token } from '../../../src/types.ts';

// v2: conservation/refixation rebuilds now include the <EOF-token>'s
// originalText (it absorbs consumed trailing comments), fixing a false-positive
// `text-loss` on inputs whose last token is a comment. Reports generated by v1
// are not comparable to v2 for these kinds.
export const ORACLE_VERSION = 'fuzz/oracles v2';

/** Hard cap for embedded detail strings so reports stay small and heap-safe. */
function cap(text: string, max = 300): string {
  return text.length <= max ? text : `${text.slice(0, max)}…(+${text.length - max})`;
}

// ---------------------------------------------------------------------------
// Preprocessing (mirrors src/tokenizer.ts; keep in sync deliberately)
// ---------------------------------------------------------------------------

/**
 * css-syntax-3 § 3.3 #input-preprocessing: CRLF/CR/FF → LF, NUL → U+FFFD,
 * lone surrogates → U+FFFD (valid surrogate pairs preserved).
 * Duplicated here intentionally so the oracle can compare against the exact
 * bytes the tokenizer is specified to see; if tokenizer.ts changes, this
 * MUST change with it (guarded by tests/fuzz-oracles.test.ts).
 */
export function preprocessInput(input: string): string {
  return input
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .replace(/\f/g, '\n')
    // eslint-disable-next-line no-control-regex
    .replace(/\0/g, '\uFFFD')
    .replace(/[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/g, '\uFFFD');
}

// ---------------------------------------------------------------------------
// Structural minimal typings (avoid importing CSSOM classes; duck-typed like
// fuzz/css-fuzz/src/target-cssomnom.ts to stay decoupled from internals)
// ---------------------------------------------------------------------------

interface RuleLike {
  cssText?: string;
}

interface SheetLike {
  cssRules: {
    length: number;
    item(index: number): RuleLike | null;
  };
}

interface StyleLike {
  getPropertyValue(property: string): string;
}

/** Serialize a parsed stylesheet the way the existing fuzz target does: per-rule `cssText`. */
export function serializeSheet(sheet: SheetLike): string {
  const parts: string[] = [];
  for (let i = 0; i < sheet.cssRules.length; i++) {
    const rule = sheet.cssRules.item(i);
    parts.push(rule?.cssText ?? '');
  }
  return parts.join('\n');
}

// ---------------------------------------------------------------------------
// Findings
// ---------------------------------------------------------------------------

export type InvariantKind =
  | 'fixpoint-unstable'
  | 'rules-dropped-on-reparse'
  | 'parse-threw'
  | 'serialize-threw'
  | 'token-gap'
  | 'token-overlap'
  | 'text-loss'
  | 'token-refixate'
  | 'stream-divergence'
  | 'valid-value-dropped';

export interface Finding {
  kind: InvariantKind;
  /** Short human-readable description, capped. */
  detail: string;
  expected?: string;
  actual?: string;
  /** First divergence offset into the relevant string, when meaningful. */
  offset?: number;
}

export interface CheckOptions {
  /** Also run chunked-streaming equivalence (slightly slower). Default true. */
  streaming?: boolean;
  /** Skip inputs longer than this (chars). Default 200_000. */
  maxInputChars?: number;
}

export interface CheckResult {
  inputLength: number;
  findings: Finding[];
}

// ---------------------------------------------------------------------------
// Oracle 1: serialization fixpoint
// ---------------------------------------------------------------------------

export function checkFixpoint(input: string): Finding[] {
  const findings: Finding[] = [];
  let sheet1: SheetLike;
  try {
    sheet1 = parseToSheet(input);
  } catch (err) {
    findings.push({
      kind: 'parse-threw',
      detail: `first parse threw ${errName(err)}: ${cap(errMessage(err))}`,
    });
    return findings;
  }

  let s1: string;
  try {
    s1 = serializeSheet(sheet1);
  } catch (err) {
    findings.push({
      kind: 'serialize-threw',
      detail: `first serialize threw ${errName(err)}: ${cap(errMessage(err))}`,
    });
    return findings;
  }

  let sheet2: SheetLike;
  try {
    sheet2 = parseToSheet(s1);
  } catch (err) {
    findings.push({
      kind: 'parse-threw',
      detail: `re-parse of own output threw ${errName(err)}: ${cap(errMessage(err))}`,
      expected: cap(s1),
    });
    return findings;
  }

  const rc1 = sheet1.cssRules.length;
  const rc2 = sheet2.cssRules.length;
  if (rc2 < rc1) {
    findings.push({
      kind: 'rules-dropped-on-reparse',
      detail: `re-parse dropped rules: ${rc1} -> ${rc2}`,
      expected: String(rc1),
      actual: String(rc2),
    });
  }

  let s2: string;
  try {
    s2 = serializeSheet(sheet2);
  } catch (err) {
    findings.push({
      kind: 'serialize-threw',
      detail: `second serialize threw ${errName(err)}: ${cap(errMessage(err))}`,
    });
    return findings;
  }

  if (s1 !== s2) {
    const offset = firstDiffOffset(s1, s2);
    findings.push({
      kind: 'fixpoint-unstable',
      detail: `serialize∘parse is not idempotent (len ${s1.length} -> ${s2.length})`,
      expected: cap(s1),
      actual: cap(s2),
      offset,
    });
  }
  return findings;
}

// ---------------------------------------------------------------------------
// Oracles 2–4: token-level conservation / refixation / streaming
// ---------------------------------------------------------------------------

/**
 * Drop the trailing EOF token for *content* comparisons.
 *
 * The <EOF-token> is a conceptual sentinel (css-syntax-3 § 5.3
 * #parser-definitions) with no width/span constraints of its own, so it must
 * not participate in structural (contiguity) assertions — but note that this
 * tokenizer folds consumed trailing comment bytes into the EOF token's span:
 * "consume comments" runs as step 1 of #consume-token (css-syntax-3 § 4.3.1)
 * and #consume-comment "returns nothing" (§ 4.3.2), so comments never become a
 * token of their own. Text reconstruction must therefore go through
 * {@link rebuiltTextMatches}, which includes the EOF token's `originalText`.
 */
export function contentTokens(tokens: readonly Token[]): Token[] {
  const end = tokens.length > 0 && tokens[tokens.length - 1].type === 'EOF' ? tokens.length - 1 : tokens.length;
  return tokens.slice(0, end);
}

/** Pure helper (exported for unit tests): concatenate every token's raw text. */
export function concatOriginalText(tokens: readonly Token[]): string {
  let rebuilt = '';
  for (const tok of tokens) rebuilt += tok.originalText ?? '';
  return rebuilt;
}

/**
 * Pure helper (exported for unit tests): does concat(originalText) over ALL
 * tokens — INCLUDING the possibly non-empty-text <EOF-token> — reproduce the
 * preprocessed input byte-for-byte?
 *
 * Returns `{ok: true, offset: -1}` on success; on mismatch returns the first
 * differing index into the preprocessed input (equal to min(len) when one side
 * is a prefix of the other).
 */
export function rebuiltTextMatches(tokens: readonly Token[], preprocessed: string): { ok: boolean; offset: number } {
  const rebuilt = concatOriginalText(tokens);
  if (rebuilt === preprocessed) return { ok: true, offset: -1 };
  return { ok: false, offset: firstDiffOffset(preprocessed, rebuilt) };
}

/** Pure helper (exported for unit tests): offset gaps/overlaps in a token slice. */
export function detectContiguityProblems(tokens: readonly Token[]): Finding[] {
  const findings: Finding[] = [];
  let expectedStart = 0;
  for (let i = 0; i < tokens.length; i++) {
    const tok = tokens[i];
    const start = tok.startIndex ?? expectedStart;
    const end = tok.endIndex ?? start;
    if (start > expectedStart) {
      findings.push({
        kind: 'token-gap',
        detail: `gap of ${start - expectedStart} code point(s) before token #${i} (${tok.type})`,
        offset: expectedStart,
        expected: String(expectedStart),
        actual: String(start),
      });
    } else if (start < expectedStart) {
      findings.push({
        kind: 'token-overlap',
        detail: `overlap of ${expectedStart - start} code point(s) before token #${i} (${tok.type})`,
        offset: start,
        expected: String(expectedStart),
        actual: String(start),
      });
    }
    if (end >= start) {
      expectedStart = end;
    }
  }
  return findings;
}

export function checkTokenConservation(input: string): Finding[] {
  const findings: Finding[] = [];
  let tokens: Token[];
  try {
    // Full stream INCLUDING the trailing <EOF-token>: its originalText may be
    // non-empty (it absorbs consumed trailing comments — css-syntax-3 § 4.3.1
    // #consume-token step 1 + § 4.3.2 #consume-comment) and is required for
    // exact text reconstruction below.
    tokens = tokenize(input);
  } catch (err) {
    findings.push({
      kind: 'parse-threw',
      detail: `tokenize() threw ${errName(err)}: ${cap(errMessage(err))}`,
    });
    return findings;
  }

  // Contiguity over content tokens only: the <EOF-token> is a sentinel with no
  // span constraints (§ 5.3 #parser-definitions), so it stays out of the
  // structural gap/overlap assertion.
  findings.push(...detectContiguityProblems(contentTokens(tokens)));

  // css-syntax-3 § 8 #serialization explicitly permits implementations to
  // preserve comments, provided this has no effect on parsing; folding their
  // bytes into the following token's (or EOF's) originalText keeps the token
  // stream a partition of the preprocessed input. Rebuild over ALL tokens —
  // including EOF — must reproduce it exactly (css-syntax-3 § 3.3).
  const pre = preprocessInput(input);
  const match = rebuiltTextMatches(tokens, pre);
  if (!match.ok) {
    const rebuilt = concatOriginalText(tokens);
    findings.push({
      kind: 'text-loss',
      detail: `concat(token.originalText) !== preprocessed input (len ${pre.length} -> ${rebuilt.length})`,
      offset: match.offset,
      expected: cap(pre.slice(Math.max(0, match.offset - 20), match.offset + 40)),
      actual: cap(rebuilt.slice(Math.max(0, match.offset - 20), match.offset + 40)),
    });
  }
  return findings;
}

export function checkTokenRefixation(input: string): Finding[] {
  // Rebuild from ALL tokens including the <EOF-token> so retokenization covers
  // the full input (trailing comments folded into EOF must survive re-parse of
  // their bytes too). Both sides are preprocessed text: tokenize(input) and
  // tokenize(rebuilt) slice the same effective stream (preprocessing is
  // idempotent), so elementwise comparison is well-defined.
  const tokens = tokenize(input);
  const rebuilt = concatOriginalText(tokens);

  const again = tokenize(rebuilt);
  if (again.length !== tokens.length) {
    return [
      {
        kind: 'token-refixate',
        detail: `retokenize changed token count: ${tokens.length} -> ${again.length}`,
        expected: String(tokens.length),
        actual: String(again.length),
      },
    ];
  }
  for (let i = 0; i < tokens.length; i++) {
    if (tokens[i].type !== again[i].type || tokens[i].originalText !== again[i].originalText) {
      return [
        {
          kind: 'token-refixate',
          detail: `retokenize diverged at token #${i}: ${tokens[i].type}/${JSON.stringify(cap(tokens[i].originalText ?? '', 60))} vs ${again[i].type}/${JSON.stringify(cap(again[i].originalText ?? '', 60))}`,
          offset: tokens[i].startIndex,
        },
      ];
    }
  }
  return [];
}

/**
 * Feed the input to StreamingTokenizer one chunk at a time, with chunk sizes
 * derived deterministically from the stream position (no RNG is involved) and
 * require the same (type, originalText) sequence as batch tokenize().
 * Mirrors the drain pattern used in tests/css-fuzz-cssomnom.test.ts.
 */
export function checkStreamingEquivalence(input: string): Finding[] {
  const oneShot = contentTokens(tokenize(input));

  const streamed: Token[] = [];
  try {
    const tokenizer = new StreamingTokenizer();
    // Deterministic split: alternating sizes 1..17 derived from position.
    let pos = 0;
    let size = 3;
    while (pos < input.length) {
      size = (size * 7 + 11 + (pos % 5)) % 17 + 1;
      const chunk = input.slice(pos, pos + size);
      pos += size;
      tokenizer.appendChunk(chunk);
      streamed.push(...contentTokens(tokenizer.getTokens()));
    }
    tokenizer.close();
    streamed.push(...contentTokens(tokenizer.getTokens()));
  } catch (err) {
    return [
      {
        kind: 'stream-divergence',
        detail: `StreamingTokenizer threw ${errName(err)}: ${cap(errMessage(err))}`,
      },
    ];
  }

  if (streamed.length !== oneShot.length) {
    return [
      {
        kind: 'stream-divergence',
        detail: `streamed token count ${streamed.length} != one-shot ${oneShot.length}`,
        expected: String(oneShot.length),
        actual: String(streamed.length),
      },
    ];
  }
  for (let i = 0; i < oneShot.length; i++) {
    if (oneShot[i].type !== streamed[i].type || oneShot[i].originalText !== streamed[i].originalText) {
      return [
        {
          kind: 'stream-divergence',
          detail: `streamed token #${i} differs: ${streamed[i].type}/${JSON.stringify(cap(streamed[i].originalText ?? '', 60))} vs one-shot ${oneShot[i].type}/${JSON.stringify(cap(oneShot[i].originalText ?? '', 60))}`,
          offset: oneShot[i].startIndex,
        },
      ];
    }
  }
  return [];
}

// ---------------------------------------------------------------------------
// Combined entry point
// ---------------------------------------------------------------------------

export function checkInput(input: string, options: CheckOptions = {}): CheckResult {
  const maxChars = options.maxInputChars ?? 200_000;
  if (input.length > maxChars) {
    return { inputLength: input.length, findings: [] };
  }
  const findings: Finding[] = [];
  findings.push(...checkFixpoint(input));
  findings.push(...checkTokenConservation(input));
  if (findings.filter((f) => f.kind.startsWith('token') || f.kind === 'text-loss').length === 0) {
    findings.push(...checkTokenRefixation(input));
  }
  if ((options.streaming ?? true) && input.length <= 50_000) {
    findings.push(...checkStreamingEquivalence(input));
  }
  return { inputLength: input.length, findings };
}

// ---------------------------------------------------------------------------
// Valid-subset helpers (used by valid-subset.ts)
// ---------------------------------------------------------------------------

interface StyleRuleHost extends RuleLike {
  style?: StyleLike;
}

/**
 * Parse `.o{prop:value}`-style snippet and return the surviving declaration
 * value for `property` ('' if the rule or declaration was dropped). A
 * grammar-valid declaration must never be dropped by a conforming recovery
 * parser.
 */
export function parseDeclarationValue(snippet: string, property: string): string {
  const sheet = parseToSheet(snippet) as unknown as { cssRules: { length: number; item(i: number): StyleRuleHost | null } };
  for (let i = 0; i < sheet.cssRules.length; i++) {
    const rule = sheet.cssRules.item(i);
    if (rule && typeof rule === 'object' && 'style' in rule && rule.style) {
      try {
        return rule.style.getPropertyValue(property);
      } catch {
        return '';
      }
    }
  }
  return '';
}

// ---------------------------------------------------------------------------
// Internal plumbing
// ---------------------------------------------------------------------------

function parseToSheet(input: string): SheetLike {
  return parse(input) as unknown as SheetLike;
}

function errName(err: unknown): string {
  return err instanceof Error ? err.name : typeof err;
}

function errMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

function firstDiffOffset(a: string, b: string): number {
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) {
    if (a[i] !== b[i]) return i;
  }
  return n;
}
