/**
 * Overlay reproducer for KI-36: 122 generated shorthands are missing from the
 * runtime expansion table, so setProperty() never expands them into longhands
 * and cascade order is silently corrupted.
 *
 * cssom-1 § 6.4.1 "Declaration blocks" (#concept-declarations-specified-order,
 * submodules/csswg-drafts/cssom-1/Overview.bs:2243-2245) is load-bearing:
 *
 *   The specified order for declarations is the same as specified, but with
 *   shorthand properties expanded into their longhand properties, in canonical
 *   order. If a property is specified more than once (after shorthand
 *   expansion), only the one with greatest cascading order must be represented,
 *   at the same relative position as it was specified.
 *
 * css-gaps-1 § 3 "Row Gap / Column Gap / Gap Shorthand" (#gap-shorthand,
 * submodules/csswg-drafts/css-gaps-1/Overview.bs:236) defines gap as
 * "a shorthand that sets 'row-gap' and 'column-gap' in one declaration", and
 * css-transitions-1 § 2.5 (Overview.bs:510) defines transition as combining its
 * longhands into a single property. A CSSStyleDeclaration that stores such
 * shorthands verbatim violates both obligations at once:
 *
 *   1. getPropertyValue('row-gap') returns "" after setProperty('gap','10px')
 *      although the declaration block conceptually contains row-gap: 10px
 *      (no expansion happened).
 *   2. When a longhand overrides one leg of an unexpanded shorthand, the
 *      serialized cssText keeps BOTH declarations ("gap: 10px; row-gap:
 *      20px;") or keeps the stale shorthand after it lost ("row-gap: 30px;
 *      gap: 10px;" with row-gap still reading 30px) - re-parsing that text
 *      preserves the wrong winner instead of the greatest cascading order,
 *      corrupting the cascade across round-trips.
 *
 * Project-contract anchor: AGENTS.md "Automation Over Hardcoding" requires
 * spec-derived data to flow from codegen into runtime; src/data/gen/
 * shorthands.ts (SHORTHANDS_DATA, 165 entries generated by scripts/codegen/
 * generate_shorthands.ts) exists but src/shorthands.ts SHORTHANDS (~L1943)
 * hand-wires only 44 entries, leaving 122 generated shorthands - including
 * gap, transition, animation, grid, columns, place-items/place-content/
 * place-self, column-rule, text-decoration, mask and offset - dead data.
 *
 * Distinctness: KI-112/113 cover font shorthand grammar roots; KI-114/116
 * cover expandBorderImage quoted-url handling. This issue covers the missing
 * table coverage itself (shorthands absent from SHORTHANDS entirely).
 *
 * Asserts the SAFE contract: setting a registered-family shorthand must
 * expand into its longhands and preserve greatest-cascading-order winners.
 *
 * Reproduces: KI-36
 */
import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { CSSStyleDeclaration } from '../../src/index.ts';
// @generated data table: src/data/gen/shorthands.ts (SHORTHANDS_DATA)
import { SHORTHANDS_DATA } from '../../src/data/gen/shorthands.ts';
// runtime expansion table: src/shorthands.ts (~L1943)
import { SHORTHANDS } from '../../src/shorthands.ts';

// Reproducer constants mirrored in specs/system/variables/shorthands-budget.vars.yaml:
const GENERATED_SHORTHAND_COVERAGE_MIN = 165; // entries in src/data/gen/shorthands.ts that must resolve at runtime
const CASCADE_WINNER_FLIP_BUDGET = 0; // zero stale-shorthand round-trip corruptions allowed

// Verifies: SYS-REQ-260823-SHX6 (KI-36 reproducer suite: codegen-backed shorthand expansion and cascade-order contract)
// reqproof:proptest:skip assertion-only known-issue overlay harness driving live parser/CSSOM object graphs; verdict exists only as pass/fail assertions with no comparable return value
describe('KI-36 shorthand expansion table completeness', () => {
  test('positive control: margin shorthand expands into longhands', () => {
    const style = new CSSStyleDeclaration();
    style.setProperty('margin', '1px');
    assert.equal(style.getPropertyValue('margin-top'), '1px');
    style.setProperty('margin-top', '5px');
    assert.equal(style.getPropertyValue('margin-top'), '5px');
    assert.equal(style.getPropertyValue('margin-left'), '1px');
  });

  // Reproduces: KI-36
  test(`all ${GENERATED_SHORTHAND_COVERAGE_MIN} generated shorthands resolve in the runtime expansion table`, () => {
    const runtimeCount = Object.keys(SHORTHANDS).length;
    const covered = Object.keys(SHORTHANDS_DATA).filter((k) => k in SHORTHANDS).length;
    assert.ok(
      runtimeCount >= GENERATED_SHORTHAND_COVERAGE_MIN && covered === Object.keys(SHORTHANDS_DATA).length,
      `KI-36: runtime SHORTHANDS table covers ${covered}/${Object.keys(SHORTHANDS_DATA).length} generated shorthands (runtime count ${runtimeCount}); AGENTS.md Automation Over Hardcoding requires codegen output to back the runtime table`,
    );
  });

  // Reproduces: KI-36
  test('gap shorthand expands so row-gap/column-gap reflect the value', () => {
    const style = new CSSStyleDeclaration();
    style.setProperty('gap', '10px');
    assert.equal(
      style.getPropertyValue('row-gap'),
      '10px',
      `KI-36: setProperty('gap','10px') must expand per cssom-1 #concept-declarations-specified-order; getPropertyValue('row-gap') returned ${JSON.stringify(style.getPropertyValue('row-gap'))}`,
    );
    assert.equal(style.getPropertyValue('column-gap'), '10px');
  });

  // Reproduces: KI-36
  test(`cssText preserves greatest cascading order (${CASCADE_WINNER_FLIP_BUDGET} flips allowed)`, () => {
    // Leg A: longhand override of an unexpanded shorthand must not keep the stale shorthand first
    const a = new CSSStyleDeclaration();
    a.setProperty('gap', '10px');
    a.setProperty('row-gap', '20px');
    assert.ok(
      !a.cssText.includes('gap:'),
      `KI-36: cssText kept the unexpanded 'gap' shorthand beside the overriding longhand: ${JSON.stringify(a.cssText)}; re-parsing this text must yield row-gap:20px/column-gap:10px`,
    );
    // Leg B: later shorthand must win over earlier longhand
    const b = new CSSStyleDeclaration();
    b.setProperty('row-gap', '30px');
    b.setProperty('gap', '10px');
    assert.equal(
      b.getPropertyValue('row-gap'),
      '10px',
      `KI-36: later 'gap' declaration has greatest cascading order (cssom-1 Overview.bs:2243-2245); row-gap read ${JSON.stringify(b.getPropertyValue('row-gap'))} from cssText ${JSON.stringify(b.cssText)}`,
    );
  });
});
